/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_fenetre_Ajouter (void);
GtkWidget* create_gestion_capteur (void);
GtkWidget* create_fenetre_Modifier (void);
GtkWidget* create_fenetre_Accueil (void);
GtkWidget* create_fenetre_Alarmente (void);
