/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_Ajouter (void)
{
  GtkWidget *fenetre_Ajouter;
  GtkWidget *fixed1;
  GtkWidget *entryNom;
  GtkWidget *entryMarque;
  GtkWidget *entryReference;
  GtkObject *spinbuttonmin_adj;
  GtkWidget *spinbuttonmin;
  GtkObject *spinbuttonmax_adj;
  GtkWidget *spinbuttonmax;
  GtkWidget *buttonAnnuler;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label11;
  GtkWidget *buttonOk;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label10;
  GtkWidget *label5;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkWidget *label3;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *label4;
  GtkWidget *radiobutton2;
  GtkWidget *label20;
  GtkWidget *label36;
  GtkWidget *label35;

  fenetre_Ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_Ajouter, 500, 500);
  gtk_window_set_title (GTK_WINDOW (fenetre_Ajouter), _("Ajouter"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_Ajouter), fixed1);

  entryNom = gtk_entry_new ();
  gtk_widget_show (entryNom);
  gtk_fixed_put (GTK_FIXED (fixed1), entryNom, 128, 136);
  gtk_widget_set_size_request (entryNom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom), 8226);

  entryMarque = gtk_entry_new ();
  gtk_widget_show (entryMarque);
  gtk_fixed_put (GTK_FIXED (fixed1), entryMarque, 128, 176);
  gtk_widget_set_size_request (entryMarque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMarque), 8226);

  entryReference = gtk_entry_new ();
  gtk_widget_show (entryReference);
  gtk_fixed_put (GTK_FIXED (fixed1), entryReference, 128, 96);
  gtk_widget_set_size_request (entryReference, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryReference), 8226);

  spinbuttonmin_adj = gtk_adjustment_new (1, 0, 10, 1, 10, 10);
  spinbuttonmin = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmin_adj), 1, 0);
  gtk_widget_show (spinbuttonmin);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonmin, 200, 264);
  gtk_widget_set_size_request (spinbuttonmin, 60, 27);

  spinbuttonmax_adj = gtk_adjustment_new (1, 40, 50, 1, 10, 10);
  spinbuttonmax = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmax_adj), 1, 0);
  gtk_widget_show (spinbuttonmax);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbuttonmax, 320, 264);
  gtk_widget_set_size_request (spinbuttonmax, 60, 27);

  buttonAnnuler = gtk_button_new ();
  gtk_widget_show (buttonAnnuler);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonAnnuler, 288, 392);
  gtk_widget_set_size_request (buttonAnnuler, 112, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonAnnuler), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox3), label11, FALSE, FALSE, 0);

  buttonOk = gtk_button_new ();
  gtk_widget_show (buttonOk);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonOk, 80, 392);
  gtk_widget_set_size_request (buttonOk, 104, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonOk), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox2), label10, FALSE, FALSE, 0);

  label5 = gtk_label_new (_("Ajouter capteur"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 104, 24);
  gtk_widget_set_size_request (label5, 168, 32);
  gtk_misc_set_alignment (GTK_MISC (label5), 0.5, 0.48);
  gtk_misc_set_padding (GTK_MISC (label5), 0, 5);

  label2 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 16, 176);
  gtk_widget_set_size_request (label2, 105, 25);

  label1 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 24, 136);
  gtk_widget_set_size_request (label1, 81, 25);

  label3 = gtk_label_new (_("Reference :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 24, 96);
  gtk_widget_set_size_request (label3, 97, 25);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("temperature"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton1, 344, 168);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  label4 = gtk_label_new (_("Type :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 352, 88);
  gtk_widget_set_size_request (label4, 56, 24);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("humidite"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), radiobutton2, 344, 136);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  label20 = gtk_label_new (_("valeurs :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed1), label20, 8, 256);
  gtk_widget_set_size_request (label20, 168, 32);

  label36 = gtk_label_new (_("max"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed1), label36, 320, 232);
  gtk_widget_set_size_request (label36, 49, 17);

  label35 = gtk_label_new (_("min"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed1), label35, 200, 232);
  gtk_widget_set_size_request (label35, 49, 17);

  g_signal_connect ((gpointer) buttonAnnuler, "clicked",
                    G_CALLBACK (on_buttonAnnuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonOk, "clicked",
                    G_CALLBACK (on_buttonOk_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_Ajouter, fenetre_Ajouter, "fenetre_Ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, entryNom, "entryNom");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, entryMarque, "entryMarque");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, entryReference, "entryReference");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, spinbuttonmin, "spinbuttonmin");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, spinbuttonmax, "spinbuttonmax");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, buttonAnnuler, "buttonAnnuler");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, image4, "image4");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label11, "label11");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, buttonOk, "buttonOk");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label10, "label10");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label2, "label2");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label1, "label1");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label3, "label3");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label20, "label20");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label36, "label36");
  GLADE_HOOKUP_OBJECT (fenetre_Ajouter, label35, "label35");

  return fenetre_Ajouter;
}

GtkWidget*
create_gestion_capteur (void)
{
  GtkWidget *gestion_capteur;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *entry10;
  GtkWidget *buttonSupprimer;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image10;
  GtkWidget *label17;
  GtkWidget *buttonModifier;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label16;
  GtkWidget *buttonAfficher;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label14;
  GtkWidget *button_Retour_gestion;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image12;
  GtkWidget *label19;
  GtkWidget *buttonRechercher;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label13;
  GtkWidget *label18;
  GtkWidget *label28;
  GtkWidget *buttonAjouter;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label15;
  GtkWidget *button_alarmentes;

  gestion_capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_capteur), _("Gestion Capteur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (gestion_capteur), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 8, 160);
  gtk_widget_set_size_request (treeview1, 552, 208);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed2), entry10, 256, 80);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  buttonSupprimer = gtk_button_new ();
  gtk_widget_show (buttonSupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonSupprimer, 584, 336);
  gtk_widget_set_size_request (buttonSupprimer, 112, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonSupprimer), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox9), image10, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox9), label17, FALSE, FALSE, 0);

  buttonModifier = gtk_button_new ();
  gtk_widget_show (buttonModifier);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonModifier, 584, 288);
  gtk_widget_set_size_request (buttonModifier, 112, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonModifier), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox8), label16, FALSE, FALSE, 0);

  buttonAfficher = gtk_button_new ();
  gtk_widget_show (buttonAfficher);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAfficher, 584, 176);
  gtk_widget_set_size_request (buttonAfficher, 112, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonAfficher), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  button_Retour_gestion = gtk_button_new ();
  gtk_widget_show (button_Retour_gestion);
  gtk_fixed_put (GTK_FIXED (fixed2), button_Retour_gestion, 280, 408);
  gtk_widget_set_size_request (button_Retour_gestion, 120, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_Retour_gestion), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox10), image12, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox10), label19, FALSE, FALSE, 0);

  buttonRechercher = gtk_button_new ();
  gtk_widget_show (buttonRechercher);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonRechercher, 440, 72);
  gtk_widget_set_size_request (buttonRechercher, 144, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonRechercher), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox5), label13, FALSE, FALSE, 0);

  label18 = gtk_label_new (_("Gestion des capteurs"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 216, 0);
  gtk_widget_set_size_request (label18, 216, 48);

  label28 = gtk_label_new (_("entry reference"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed2), label28, 128, 80);
  gtk_widget_set_size_request (label28, 112, 32);

  buttonAjouter = gtk_button_new ();
  gtk_widget_show (buttonAjouter);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonAjouter, 584, 232);
  gtk_widget_set_size_request (buttonAjouter, 112, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonAjouter), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox7), label15, FALSE, FALSE, 0);

  button_alarmentes = gtk_button_new_with_mnemonic (_("Capteurs Alarmentes"));
  gtk_widget_show (button_alarmentes);
  gtk_fixed_put (GTK_FIXED (fixed2), button_alarmentes, 568, 416);
  gtk_widget_set_size_request (button_alarmentes, 176, 72);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonSupprimer, "clicked",
                    G_CALLBACK (on_buttonSupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonModifier, "clicked",
                    G_CALLBACK (on_buttonModifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAfficher, "clicked",
                    G_CALLBACK (on_buttonAfficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_Retour_gestion, "clicked",
                    G_CALLBACK (on_button_Retour_gestion_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonRechercher, "clicked",
                    G_CALLBACK (on_buttonRechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAjouter, "clicked",
                    G_CALLBACK (on_buttonAjouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_alarmentes, "clicked",
                    G_CALLBACK (on_button_alarmentes_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_capteur, gestion_capteur, "gestion_capteur");
  GLADE_HOOKUP_OBJECT (gestion_capteur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (gestion_capteur, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_capteur, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (gestion_capteur, buttonSupprimer, "buttonSupprimer");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image10, "image10");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_capteur, buttonModifier, "buttonModifier");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label16, "label16");
  GLADE_HOOKUP_OBJECT (gestion_capteur, buttonAfficher, "buttonAfficher");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label14, "label14");
  GLADE_HOOKUP_OBJECT (gestion_capteur, button_Retour_gestion, "button_Retour_gestion");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image12, "image12");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label19, "label19");
  GLADE_HOOKUP_OBJECT (gestion_capteur, buttonRechercher, "buttonRechercher");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label13, "label13");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label18, "label18");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label28, "label28");
  GLADE_HOOKUP_OBJECT (gestion_capteur, buttonAjouter, "buttonAjouter");
  GLADE_HOOKUP_OBJECT (gestion_capteur, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_capteur, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_capteur, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_capteur, label15, "label15");
  GLADE_HOOKUP_OBJECT (gestion_capteur, button_alarmentes, "button_alarmentes");

  return gestion_capteur;
}

GtkWidget*
create_fenetre_Modifier (void)
{
  GtkWidget *fenetre_Modifier;
  GtkWidget *fixed3;
  GtkWidget *entryNom1;
  GtkWidget *label26;
  GtkWidget *entryMarque1;
  GtkObject *spinbuttonmin1_adj;
  GtkWidget *spinbuttonmin1;
  GtkObject *spinbuttonmax1_adj;
  GtkWidget *spinbuttonmax1;
  GtkWidget *buttonAnnuler1;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image14;
  GtkWidget *label30;
  GtkWidget *checkbutton1;
  GtkWidget *buttonOk1;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label29;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *radiobutton3;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label37;
  GtkWidget *label38;
  GtkWidget *label34;

  fenetre_Modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_Modifier, 500, 500);
  gtk_window_set_title (GTK_WINDOW (fenetre_Modifier), _("Modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (fenetre_Modifier), fixed3);
  gtk_widget_set_size_request (fixed3, 500, 500);

  entryNom1 = gtk_entry_new ();
  gtk_widget_show (entryNom1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryNom1, 176, 80);
  gtk_widget_set_size_request (entryNom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryNom1), 8226);

  label26 = gtk_label_new (_("Nouveau Marque :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed3), label26, 0, 128);
  gtk_widget_set_size_request (label26, 160, 24);

  entryMarque1 = gtk_entry_new ();
  gtk_widget_show (entryMarque1);
  gtk_fixed_put (GTK_FIXED (fixed3), entryMarque1, 176, 128);
  gtk_widget_set_size_request (entryMarque1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryMarque1), 8226);

  spinbuttonmin1_adj = gtk_adjustment_new (1, 0, 10, 1, 10, 10);
  spinbuttonmin1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmin1_adj), 1, 0);
  gtk_widget_show (spinbuttonmin1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonmin1, 200, 208);
  gtk_widget_set_size_request (spinbuttonmin1, 60, 27);

  spinbuttonmax1_adj = gtk_adjustment_new (2000, 40, 50, 1, 10, 10);
  spinbuttonmax1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmax1_adj), 1, 0);
  gtk_widget_show (spinbuttonmax1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbuttonmax1, 296, 208);
  gtk_widget_set_size_request (spinbuttonmax1, 60, 27);

  buttonAnnuler1 = gtk_button_new ();
  gtk_widget_show (buttonAnnuler1);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonAnnuler1, 296, 376);
  gtk_widget_set_size_request (buttonAnnuler1, 104, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonAnnuler1), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image14 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox12), image14, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox12), label30, FALSE, FALSE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("confirmer les modifications"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 152, 304);
  gtk_widget_set_size_request (checkbutton1, 232, 32);

  buttonOk1 = gtk_button_new ();
  gtk_widget_show (buttonOk1);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonOk1, 80, 376);
  gtk_widget_set_size_request (buttonOk1, 80, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonOk1), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox11), label29, FALSE, FALSE, 0);

  label21 = gtk_label_new (_("Modifier"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 160, 24);
  gtk_widget_set_size_request (label21, 80, 24);

  label22 = gtk_label_new (_("Nouveau Nom :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 16, 88);
  gtk_widget_set_size_request (label22, 128, 24);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("humidite"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton4, 416, 144);
  gtk_widget_set_size_request (radiobutton4, 128, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("temperature"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton3, 416, 112);
  gtk_widget_set_size_request (radiobutton3, 120, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  label27 = gtk_label_new (_("Nouveau Type :"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed3), label27, 400, 72);
  gtk_widget_set_size_request (label27, 136, 24);

  label28 = gtk_label_new (_("valeurs :"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed3), label28, 0, 208);
  gtk_widget_set_size_request (label28, 160, 32);

  label37 = gtk_label_new (_("min"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed3), label37, 208, 176);
  gtk_widget_set_size_request (label37, 49, 17);

  label38 = gtk_label_new (_("max"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed3), label38, 296, 176);
  gtk_widget_set_size_request (label38, 49, 17);

  label34 = gtk_label_new ("");
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed3), label34, 288, 24);
  gtk_widget_set_size_request (label34, 96, 24);

  g_signal_connect ((gpointer) buttonAnnuler1, "clicked",
                    G_CALLBACK (on_buttonAnnuler1_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonOk1, "clicked",
                    G_CALLBACK (on_buttonOk1_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4, "toggled",
                    G_CALLBACK (on_radiobutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3, "toggled",
                    G_CALLBACK (on_radiobutton3_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_Modifier, fenetre_Modifier, "fenetre_Modifier");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, entryNom1, "entryNom1");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label26, "label26");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, entryMarque1, "entryMarque1");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, spinbuttonmin1, "spinbuttonmin1");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, spinbuttonmax1, "spinbuttonmax1");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, buttonAnnuler1, "buttonAnnuler1");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, image14, "image14");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label30, "label30");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, buttonOk1, "buttonOk1");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, image13, "image13");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label29, "label29");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label22, "label22");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, radiobutton3, "radiobutton3");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label27, "label27");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label28, "label28");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label37, "label37");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label38, "label38");
  GLADE_HOOKUP_OBJECT (fenetre_Modifier, label34, "label34");

  return fenetre_Modifier;
}

GtkWidget*
create_fenetre_Accueil (void)
{
  GtkWidget *fenetre_Accueil;
  GtkWidget *fixed4;
  GtkWidget *button_quitter;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image16;
  GtkWidget *label33;
  GtkWidget *button_accueil;

  fenetre_Accueil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_Accueil, 500, 500);
  gtk_window_set_title (GTK_WINDOW (fenetre_Accueil), _("Accueil"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (fenetre_Accueil), fixed4);
  gtk_widget_set_size_request (fixed4, 384, 192);

  button_quitter = gtk_button_new ();
  gtk_widget_show (button_quitter);
  gtk_fixed_put (GTK_FIXED (fixed4), button_quitter, 168, 320);
  gtk_widget_set_size_request (button_quitter, 144, 88);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_quitter), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image16 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox14), image16, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox14), label33, FALSE, FALSE, 0);

  button_accueil = gtk_button_new_with_mnemonic (_("Gestion Capteurs"));
  gtk_widget_show (button_accueil);
  gtk_fixed_put (GTK_FIXED (fixed4), button_accueil, 152, 144);
  gtk_widget_set_size_request (button_accueil, 184, 80);

  g_signal_connect ((gpointer) button_quitter, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button_accueil, "clicked",
                    G_CALLBACK (on_button_accueil_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_Accueil, fenetre_Accueil, "fenetre_Accueil");
  GLADE_HOOKUP_OBJECT (fenetre_Accueil, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (fenetre_Accueil, button_quitter, "button_quitter");
  GLADE_HOOKUP_OBJECT (fenetre_Accueil, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (fenetre_Accueil, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (fenetre_Accueil, image16, "image16");
  GLADE_HOOKUP_OBJECT (fenetre_Accueil, label33, "label33");
  GLADE_HOOKUP_OBJECT (fenetre_Accueil, button_accueil, "button_accueil");

  return fenetre_Accueil;
}

GtkWidget*
create_fenetre_Alarmente (void)
{
  GtkWidget *fenetre_Alarmente;
  GtkWidget *fixed5;
  GtkWidget *treeview2;
  GtkWidget *label32;
  GtkWidget *button_retour2;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image15;
  GtkWidget *label31;
  GtkWidget *buttonalarmente;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image17;
  GtkWidget *label39;

  fenetre_Alarmente = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fenetre_Alarmente, 500, 500);
  gtk_window_set_title (GTK_WINDOW (fenetre_Alarmente), _("Capteurs Alarmentes"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (fenetre_Alarmente), fixed5);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview2, 56, 96);
  gtk_widget_set_size_request (treeview2, 352, 232);

  label32 = gtk_label_new (_("Capteurs avec valeurs alarmentes"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 88, 32);
  gtk_widget_set_size_request (label32, 272, 32);

  button_retour2 = gtk_button_new ();
  gtk_widget_show (button_retour2);
  gtk_fixed_put (GTK_FIXED (fixed5), button_retour2, 288, 368);
  gtk_widget_set_size_request (button_retour2, 112, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_retour2), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image15 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox13), image15, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox13), label31, FALSE, FALSE, 0);

  buttonalarmente = gtk_button_new ();
  gtk_widget_show (buttonalarmente);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonalarmente, 112, 368);
  gtk_widget_set_size_request (buttonalarmente, 112, 48);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonalarmente), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image17 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox15), label39, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_retour2, "clicked",
                    G_CALLBACK (on_button_retour2_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonalarmente, "clicked",
                    G_CALLBACK (on_buttonalarmente_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_Alarmente, fenetre_Alarmente, "fenetre_Alarmente");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, label32, "label32");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, button_retour2, "button_retour2");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, image15, "image15");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, label31, "label31");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, buttonalarmente, "buttonalarmente");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, image17, "image17");
  GLADE_HOOKUP_OBJECT (fenetre_Alarmente, label39, "label39");

  return fenetre_Alarmente;
}

