/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *fenetre_Ajouter;
  GtkWidget *gestion_capteur;
  GtkWidget *fenetre_Modifier;
  GtkWidget *fenetre_Accueil;
   GtkWidget *fenetre_Alarmente;
#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 // fenetre_Ajouter = create_fenetre_Ajouter ();
 // gtk_widget_show (fenetre_Ajouter);
 // gestion_capteur = create_gestion_capteur ();
 // gtk_widget_show (gestion_capteur);
 // fenetre_Modifier = create_fenetre_Modifier ();
 // gtk_widget_show (fenetre_Modifier);
  fenetre_Accueil = create_fenetre_Accueil ();
  gtk_widget_show (fenetre_Accueil);
 // fenetre_Alarmente = create_fenetre_Alarmente ();
 // gtk_widget_show (fenetre_Alarmente);


  gtk_main ();
  return 0;
}

