/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_dashboard_hebergement (void)
{
  GtkWidget *dashboard_hebergement;
  GtkWidget *fixed1d;
  GtkWidget *image104;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button5;
  GtkWidget *button4;
  GtkWidget *button1;

  dashboard_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (dashboard_hebergement, 600, 600);
  gtk_window_set_title (GTK_WINDOW (dashboard_hebergement), _("Gestion des \303\251tudiants h\303\251berg\303\251s"));
  gtk_window_set_position (GTK_WINDOW (dashboard_hebergement), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (dashboard_hebergement), FALSE);

  fixed1d = gtk_fixed_new ();
  gtk_widget_show (fixed1d);
  gtk_container_add (GTK_CONTAINER (dashboard_hebergement), fixed1d);

  image104 = create_pixmap (dashboard_hebergement, "logos.png");
  gtk_widget_show (image104);
  gtk_fixed_put (GTK_FIXED (fixed1d), image104, 8, 8);
  gtk_widget_set_size_request (image104, 218, 116);

  button2 = gtk_button_new_with_mnemonic (_("Modifier un \303\251tudiant h\303\251berg\303\251"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1d), button2, 168, 224);
  gtk_widget_set_size_request (button2, 304, 72);

  button3 = gtk_button_new_with_mnemonic (_("Afficher les \303\251tudiants h\303\251berg\303\251s"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1d), button3, 168, 328);
  gtk_widget_set_size_request (button3, 304, 72);

  button5 = gtk_button_new_with_mnemonic (_("Chercher un \303\251tudiant h\303\251berg\303\251"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1d), button5, 168, 424);
  gtk_widget_set_size_request (button5, 304, 72);

  button4 = gtk_button_new_with_mnemonic (_("Liste des alarmes entre 00h et 06h"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed1d), button4, 168, 520);
  gtk_widget_set_size_request (button4, 304, 72);

  button1 = gtk_button_new_with_mnemonic (_(" Ajouter un \303\251tudiant h\303\251berg\303\251"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1d), button1, 168, 128);
  gtk_widget_set_size_request (button1, 304, 72);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button_2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button_3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button_4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button_1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dashboard_hebergement, dashboard_hebergement, "dashboard_hebergement");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, fixed1d, "fixed1d");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, image104, "image104");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button2, "button2");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button3, "button3");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button5, "button5");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button4, "button4");
  GLADE_HOOKUP_OBJECT (dashboard_hebergement, button1, "button1");

  return dashboard_hebergement;
}

GtkWidget*
create_af_alarme (void)
{
  GtkWidget *af_alarme;
  GtkWidget *fixed2d;
  GtkWidget *image105;
  GtkWidget *scrolledwindow400;
  GtkWidget *treeview_fumee;
  GtkWidget *scrolledwindow300;
  GtkWidget *treeview_mvt;
  GtkWidget *button_af_alarme;
  GtkWidget *alignment300;
  GtkWidget *hbox1;
  GtkWidget *image100;
  GtkWidget *label200;
  GtkWidget *button_mvt;
  GtkWidget *alignment704;
  GtkWidget *hbox12;
  GtkWidget *image110;
  GtkWidget *label3907;
  GtkWidget *label100;
  GtkWidget *label21001;
  GtkWidget *label21002;

  af_alarme = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (af_alarme, 824, 600);
  gtk_window_set_title (GTK_WINDOW (af_alarme), _("Liste des alarmes entre 00h et 06h"));
  gtk_window_set_position (GTK_WINDOW (af_alarme), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (af_alarme), FALSE);

  fixed2d = gtk_fixed_new ();
  gtk_widget_show (fixed2d);
  gtk_container_add (GTK_CONTAINER (af_alarme), fixed2d);

  image105 = create_pixmap (af_alarme, "logos.png");
  gtk_widget_show (image105);
  gtk_fixed_put (GTK_FIXED (fixed2d), image105, 16, 8);
  gtk_widget_set_size_request (image105, 218, 116);

  scrolledwindow400 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow400);
  gtk_fixed_put (GTK_FIXED (fixed2d), scrolledwindow400, 56, 400);
  gtk_widget_set_size_request (scrolledwindow400, 576, 184);

  treeview_fumee = gtk_tree_view_new ();
  gtk_widget_show (treeview_fumee);
  gtk_container_add (GTK_CONTAINER (scrolledwindow400), treeview_fumee);

  scrolledwindow300 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow300);
  gtk_fixed_put (GTK_FIXED (fixed2d), scrolledwindow300, 56, 160);
  gtk_widget_set_size_request (scrolledwindow300, 576, 184);

  treeview_mvt = gtk_tree_view_new ();
  gtk_widget_show (treeview_mvt);
  gtk_container_add (GTK_CONTAINER (scrolledwindow300), treeview_mvt);

  button_af_alarme = gtk_button_new ();
  gtk_widget_show (button_af_alarme);
  gtk_fixed_put (GTK_FIXED (fixed2d), button_af_alarme, 672, 224);
  gtk_widget_set_size_request (button_af_alarme, 119, 48);

  alignment300 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment300);
  gtk_container_add (GTK_CONTAINER (button_af_alarme), alignment300);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment300), hbox1);

  image100 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image100);
  gtk_box_pack_start (GTK_BOX (hbox1), image100, FALSE, FALSE, 0);

  label200 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label200);
  gtk_box_pack_start (GTK_BOX (hbox1), label200, FALSE, FALSE, 0);

  button_mvt = gtk_button_new ();
  gtk_widget_show (button_mvt);
  gtk_fixed_put (GTK_FIXED (fixed2d), button_mvt, 672, 464);
  gtk_widget_set_size_request (button_mvt, 119, 48);

  alignment704 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment704);
  gtk_container_add (GTK_CONTAINER (button_mvt), alignment704);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment704), hbox12);

  image110 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image110);
  gtk_box_pack_start (GTK_BOX (hbox12), image110, FALSE, FALSE, 0);

  label3907 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label3907);
  gtk_box_pack_start (GTK_BOX (hbox12), label3907, FALSE, FALSE, 0);

  label100 = gtk_label_new (_("<b><span color='red'> Liste des alarmes entre 00h et 06h </span></b>"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed2d), label100, 280, 16);
  gtk_widget_set_size_request (label100, 280, 56);
  gtk_label_set_use_markup (GTK_LABEL (label100), TRUE);

  label21001 = gtk_label_new (_("<b><span color='red'> Detection du mouvement </span></b>"));
  gtk_widget_show (label21001);
  gtk_fixed_put (GTK_FIXED (fixed2d), label21001, 296, 120);
  gtk_widget_set_size_request (label21001, 208, 24);
  gtk_label_set_use_markup (GTK_LABEL (label21001), TRUE);

  label21002 = gtk_label_new (_("<b><span color='red'> Detection du fum\303\251e </span></b>"));
  gtk_widget_show (label21002);
  gtk_fixed_put (GTK_FIXED (fixed2d), label21002, 288, 360);
  gtk_widget_set_size_request (label21002, 200, 24);
  gtk_label_set_use_markup (GTK_LABEL (label21002), TRUE);

  g_signal_connect ((gpointer) button_af_alarme, "clicked",
                    G_CALLBACK (on_button_af_alarme_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mvt, "clicked",
                    G_CALLBACK (on_button_mvt_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (af_alarme, af_alarme, "af_alarme");
  GLADE_HOOKUP_OBJECT (af_alarme, fixed2d, "fixed2d");
  GLADE_HOOKUP_OBJECT (af_alarme, image105, "image105");
  GLADE_HOOKUP_OBJECT (af_alarme, scrolledwindow400, "scrolledwindow400");
  GLADE_HOOKUP_OBJECT (af_alarme, treeview_fumee, "treeview_fumee");
  GLADE_HOOKUP_OBJECT (af_alarme, scrolledwindow300, "scrolledwindow300");
  GLADE_HOOKUP_OBJECT (af_alarme, treeview_mvt, "treeview_mvt");
  GLADE_HOOKUP_OBJECT (af_alarme, button_af_alarme, "button_af_alarme");
  GLADE_HOOKUP_OBJECT (af_alarme, alignment300, "alignment300");
  GLADE_HOOKUP_OBJECT (af_alarme, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (af_alarme, image100, "image100");
  GLADE_HOOKUP_OBJECT (af_alarme, label200, "label200");
  GLADE_HOOKUP_OBJECT (af_alarme, button_mvt, "button_mvt");
  GLADE_HOOKUP_OBJECT (af_alarme, alignment704, "alignment704");
  GLADE_HOOKUP_OBJECT (af_alarme, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (af_alarme, image110, "image110");
  GLADE_HOOKUP_OBJECT (af_alarme, label3907, "label3907");
  GLADE_HOOKUP_OBJECT (af_alarme, label100, "label100");
  GLADE_HOOKUP_OBJECT (af_alarme, label21001, "label21001");
  GLADE_HOOKUP_OBJECT (af_alarme, label21002, "label21002");

  return af_alarme;
}

GtkWidget*
create_af_hebergement (void)
{
  GtkWidget *af_hebergement;
  GtkWidget *fixed3d;
  GtkWidget *image106;
  GtkWidget *scrolledwindow200;
  GtkWidget *treeview_hebergement;
  GtkWidget *button_af;
  GtkWidget *alignment703;
  GtkWidget *hbox11;
  GtkWidget *image103;
  GtkWidget *label3904;
  GtkWidget *boutton501;
  GtkWidget *alignment701;
  GtkWidget *hbox9;
  GtkWidget *image101;
  GtkWidget *label3901;
  GtkWidget *ajouterd;
  GtkWidget *alignment702;
  GtkWidget *hbox10;
  GtkWidget *image102;
  GtkWidget *label3902;
  GtkWidget *label300;
  GtkWidget *label3903;

  af_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (af_hebergement, 824, 550);
  gtk_window_set_title (GTK_WINDOW (af_hebergement), _("Liste des \303\251tudiants h\303\251berg\303\251s"));
  gtk_window_set_position (GTK_WINDOW (af_hebergement), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (af_hebergement), FALSE);

  fixed3d = gtk_fixed_new ();
  gtk_widget_show (fixed3d);
  gtk_container_add (GTK_CONTAINER (af_hebergement), fixed3d);

  image106 = create_pixmap (af_hebergement, "logos.png");
  gtk_widget_show (image106);
  gtk_fixed_put (GTK_FIXED (fixed3d), image106, 32, 16);
  gtk_widget_set_size_request (image106, 218, 116);

  scrolledwindow200 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow200);
  gtk_fixed_put (GTK_FIXED (fixed3d), scrolledwindow200, 40, 152);
  gtk_widget_set_size_request (scrolledwindow200, 752, 264);

  treeview_hebergement = gtk_tree_view_new ();
  gtk_widget_show (treeview_hebergement);
  gtk_container_add (GTK_CONTAINER (scrolledwindow200), treeview_hebergement);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview_hebergement), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview_hebergement), TRUE);

  button_af = gtk_button_new ();
  gtk_widget_show (button_af);
  gtk_fixed_put (GTK_FIXED (fixed3d), button_af, 584, 432);
  gtk_widget_set_size_request (button_af, 112, 48);

  alignment703 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment703);
  gtk_container_add (GTK_CONTAINER (button_af), alignment703);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment703), hbox11);

  image103 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image103);
  gtk_box_pack_start (GTK_BOX (hbox11), image103, FALSE, FALSE, 0);

  label3904 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label3904);
  gtk_box_pack_start (GTK_BOX (hbox11), label3904, FALSE, FALSE, 0);

  boutton501 = gtk_button_new ();
  gtk_widget_show (boutton501);
  gtk_fixed_put (GTK_FIXED (fixed3d), boutton501, 344, 432);
  gtk_widget_set_size_request (boutton501, 112, 48);

  alignment701 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment701);
  gtk_container_add (GTK_CONTAINER (boutton501), alignment701);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment701), hbox9);

  image101 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image101);
  gtk_box_pack_start (GTK_BOX (hbox9), image101, FALSE, FALSE, 0);

  label3901 = gtk_label_new_with_mnemonic (_("Modider"));
  gtk_widget_show (label3901);
  gtk_box_pack_start (GTK_BOX (hbox9), label3901, FALSE, FALSE, 0);

  ajouterd = gtk_button_new ();
  gtk_widget_show (ajouterd);
  gtk_fixed_put (GTK_FIXED (fixed3d), ajouterd, 104, 432);
  gtk_widget_set_size_request (ajouterd, 112, 48);

  alignment702 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment702);
  gtk_container_add (GTK_CONTAINER (ajouterd), alignment702);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment702), hbox10);

  image102 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image102);
  gtk_box_pack_start (GTK_BOX (hbox10), image102, FALSE, FALSE, 0);

  label3902 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3902);
  gtk_box_pack_start (GTK_BOX (hbox10), label3902, FALSE, FALSE, 0);

  label300 = gtk_label_new (_("<b><span color='red'>Liste des \303\251tudiants h\303\251berg\303\251s</span></b>"));
  gtk_widget_show (label300);
  gtk_fixed_put (GTK_FIXED (fixed3d), label300, 272, 80);
  gtk_widget_set_size_request (label300, 280, 56);
  gtk_label_set_use_markup (GTK_LABEL (label300), TRUE);

  label3903 = gtk_label_new (_("<b><span color='red'>Pour supprimer clicker deux fois</span></b>"));
  gtk_widget_show (label3903);
  gtk_fixed_put (GTK_FIXED (fixed3d), label3903, 216, 496);
  gtk_widget_set_size_request (label3903, 328, 43);
  gtk_label_set_use_markup (GTK_LABEL (label3903), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label3903), 0.5, 0.45);

  g_signal_connect ((gpointer) treeview_hebergement, "row_activated",
                    G_CALLBACK (on_treeview_hebergement_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_af, "clicked",
                    G_CALLBACK (on_button_af_clicked),
                    NULL);
  g_signal_connect ((gpointer) boutton501, "clicked",
                    G_CALLBACK (on_button501_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouterd, "clicked",
                    G_CALLBACK (on_ajouterd_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (af_hebergement, af_hebergement, "af_hebergement");
  GLADE_HOOKUP_OBJECT (af_hebergement, fixed3d, "fixed3d");
  GLADE_HOOKUP_OBJECT (af_hebergement, image106, "image106");
  GLADE_HOOKUP_OBJECT (af_hebergement, scrolledwindow200, "scrolledwindow200");
  GLADE_HOOKUP_OBJECT (af_hebergement, treeview_hebergement, "treeview_hebergement");
  GLADE_HOOKUP_OBJECT (af_hebergement, button_af, "button_af");
  GLADE_HOOKUP_OBJECT (af_hebergement, alignment703, "alignment703");
  GLADE_HOOKUP_OBJECT (af_hebergement, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (af_hebergement, image103, "image103");
  GLADE_HOOKUP_OBJECT (af_hebergement, label3904, "label3904");
  GLADE_HOOKUP_OBJECT (af_hebergement, boutton501, "boutton501");
  GLADE_HOOKUP_OBJECT (af_hebergement, alignment701, "alignment701");
  GLADE_HOOKUP_OBJECT (af_hebergement, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (af_hebergement, image101, "image101");
  GLADE_HOOKUP_OBJECT (af_hebergement, label3901, "label3901");
  GLADE_HOOKUP_OBJECT (af_hebergement, ajouterd, "ajouterd");
  GLADE_HOOKUP_OBJECT (af_hebergement, alignment702, "alignment702");
  GLADE_HOOKUP_OBJECT (af_hebergement, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (af_hebergement, image102, "image102");
  GLADE_HOOKUP_OBJECT (af_hebergement, label3902, "label3902");
  GLADE_HOOKUP_OBJECT (af_hebergement, label300, "label300");
  GLADE_HOOKUP_OBJECT (af_hebergement, label3903, "label3903");

  return af_hebergement;
}

GtkWidget*
create_mod_hebergement (void)
{
  GtkWidget *mod_hebergement;
  GtkWidget *fixed4d;
  GtkWidget *mod5;
  GtkWidget *mod2;
  GtkWidget *mod3;
  GtkWidget *mod1;
  GtkWidget *mod6;
  GtkObject *mod7_adj;
  GtkWidget *mod7;
  GtkWidget *label800;
  GtkWidget *label2200;
  GtkWidget *label3600;
  GtkWidget *label600;
  GtkWidget *label500;
  GtkWidget *image107;
  GtkWidget *label1000;
  GtkWidget *label900;
  GtkWidget *modA;
  GSList *modA_group = NULL;
  GtkWidget *modB;
  GtkWidget *modC;
  GtkWidget *mod4;
  GtkWidget *label3700;
  GtkWidget *button_mod;
  GtkWidget *alignment80;
  GtkWidget *hbox4;
  GtkWidget *image40;
  GtkWidget *label12000;
  GtkWidget *check_id;
  GtkWidget *alignment700;
  GtkWidget *hbox3;
  GtkWidget *image30;
  GtkWidget *label1100;

  mod_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mod_hebergement, 784, 720);
  gtk_window_set_title (GTK_WINDOW (mod_hebergement), _("Modifier un \303\251tudiant h\303\251berg\303\251"));
  gtk_window_set_position (GTK_WINDOW (mod_hebergement), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (mod_hebergement), FALSE);

  fixed4d = gtk_fixed_new ();
  gtk_widget_show (fixed4d);
  gtk_container_add (GTK_CONTAINER (mod_hebergement), fixed4d);

  mod5 = gtk_entry_new ();
  gtk_widget_show (mod5);
  gtk_fixed_put (GTK_FIXED (fixed4d), mod5, 168, 512);
  gtk_widget_set_size_request (mod5, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod5), 8226);

  mod2 = gtk_entry_new ();
  gtk_widget_show (mod2);
  gtk_fixed_put (GTK_FIXED (fixed4d), mod2, 176, 272);
  gtk_widget_set_size_request (mod2, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod2), 8226);

  mod3 = gtk_entry_new ();
  gtk_widget_show (mod3);
  gtk_fixed_put (GTK_FIXED (fixed4d), mod3, 176, 328);
  gtk_widget_set_size_request (mod3, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod3), 8226);

  mod1 = gtk_entry_new ();
  gtk_widget_show (mod1);
  gtk_fixed_put (GTK_FIXED (fixed4d), mod1, 296, 160);
  gtk_widget_set_size_request (mod1, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod1), 8226);

  mod6 = gtk_entry_new ();
  gtk_widget_show (mod6);
  gtk_fixed_put (GTK_FIXED (fixed4d), mod6, 168, 576);
  gtk_widget_set_size_request (mod6, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (mod6), 8226);

  mod7_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  mod7 = gtk_spin_button_new (GTK_ADJUSTMENT (mod7_adj), 1, 0);
  gtk_widget_show (mod7);
  gtk_fixed_put (GTK_FIXED (fixed4d), mod7, 504, 456);
  gtk_widget_set_size_request (mod7, 60, 27);

  label800 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label800);
  gtk_fixed_put (GTK_FIXED (fixed4d), label800, 72, 336);
  gtk_widget_set_size_request (label800, 64, 16);

  label2200 = gtk_label_new (_("Bloc :"));
  gtk_widget_show (label2200);
  gtk_fixed_put (GTK_FIXED (fixed4d), label2200, 72, 392);
  gtk_widget_set_size_request (label2200, 64, 16);

  label3600 = gtk_label_new (_("Type chambre :"));
  gtk_widget_show (label3600);
  gtk_fixed_put (GTK_FIXED (fixed4d), label3600, 8, 456);
  gtk_widget_set_size_request (label3600, 112, 24);

  label600 = gtk_label_new (_("Tel :"));
  gtk_widget_show (label600);
  gtk_fixed_put (GTK_FIXED (fixed4d), label600, 72, 528);
  gtk_widget_set_size_request (label600, 56, 16);

  label500 = gtk_label_new (_("Email :"));
  gtk_widget_show (label500);
  gtk_fixed_put (GTK_FIXED (fixed4d), label500, 64, 584);
  gtk_widget_set_size_request (label500, 57, 17);

  image107 = create_pixmap (mod_hebergement, "logos.png");
  gtk_widget_show (image107);
  gtk_fixed_put (GTK_FIXED (fixed4d), image107, 16, 24);
  gtk_widget_set_size_request (image107, 218, 116);

  label1000 = gtk_label_new (_("ID :"));
  gtk_widget_show (label1000);
  gtk_fixed_put (GTK_FIXED (fixed4d), label1000, 184, 168);
  gtk_widget_set_size_request (label1000, 46, 20);

  label900 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label900);
  gtk_fixed_put (GTK_FIXED (fixed4d), label900, 64, 272);
  gtk_widget_set_size_request (label900, 80, 24);

  modA = gtk_radio_button_new_with_mnemonic (NULL, _("A"));
  gtk_widget_show (modA);
  gtk_fixed_put (GTK_FIXED (fixed4d), modA, 192, 392);
  gtk_widget_set_size_request (modA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modA), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modA));

  modB = gtk_radio_button_new_with_mnemonic (NULL, _("B"));
  gtk_widget_show (modB);
  gtk_fixed_put (GTK_FIXED (fixed4d), modB, 352, 392);
  gtk_widget_set_size_request (modB, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modB), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modB));

  modC = gtk_radio_button_new_with_mnemonic (NULL, _("C"));
  gtk_widget_show (modC);
  gtk_fixed_put (GTK_FIXED (fixed4d), modC, 528, 392);
  gtk_widget_set_size_request (modC, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (modC), modA_group);
  modA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (modC));

  mod4 = gtk_combo_box_new_text ();
  gtk_widget_show (mod4);
  gtk_fixed_put (GTK_FIXED (fixed4d), mod4, 168, 448);
  gtk_widget_set_size_request (mod4, 176, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod4), _("Individuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod4), _("Double"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mod4), _("Triple"));

  label3700 = gtk_label_new (_("Num chambre :"));
  gtk_widget_show (label3700);
  gtk_fixed_put (GTK_FIXED (fixed4d), label3700, 368, 456);
  gtk_widget_set_size_request (label3700, 112, 24);

  button_mod = gtk_button_new ();
  gtk_widget_show (button_mod);
  gtk_fixed_put (GTK_FIXED (fixed4d), button_mod, 352, 656);
  gtk_widget_set_size_request (button_mod, 120, 48);

  alignment80 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment80);
  gtk_container_add (GTK_CONTAINER (button_mod), alignment80);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment80), hbox4);

  image40 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox4), image40, FALSE, FALSE, 0);

  label12000 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label12000);
  gtk_box_pack_start (GTK_BOX (hbox4), label12000, FALSE, FALSE, 0);

  check_id = gtk_button_new ();
  gtk_widget_show (check_id);
  gtk_fixed_put (GTK_FIXED (fixed4d), check_id, 528, 152);
  gtk_widget_set_size_request (check_id, 120, 48);

  alignment700 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment700);
  gtk_container_add (GTK_CONTAINER (check_id), alignment700);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment700), hbox3);

  image30 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox3), image30, FALSE, FALSE, 0);

  label1100 = gtk_label_new_with_mnemonic (_("V\303\251rifier"));
  gtk_widget_show (label1100);
  gtk_box_pack_start (GTK_BOX (hbox3), label1100, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_mod, "clicked",
                    G_CALLBACK (on_button_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) check_id, "clicked",
                    G_CALLBACK (on_check_id_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mod_hebergement, mod_hebergement, "mod_hebergement");
  GLADE_HOOKUP_OBJECT (mod_hebergement, fixed4d, "fixed4d");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod5, "mod5");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod2, "mod2");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod3, "mod3");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod1, "mod1");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod6, "mod6");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod7, "mod7");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label800, "label800");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label2200, "label2200");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label3600, "label3600");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label600, "label600");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label500, "label500");
  GLADE_HOOKUP_OBJECT (mod_hebergement, image107, "image107");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label1000, "label1000");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label900, "label900");
  GLADE_HOOKUP_OBJECT (mod_hebergement, modA, "modA");
  GLADE_HOOKUP_OBJECT (mod_hebergement, modB, "modB");
  GLADE_HOOKUP_OBJECT (mod_hebergement, modC, "modC");
  GLADE_HOOKUP_OBJECT (mod_hebergement, mod4, "mod4");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label3700, "label3700");
  GLADE_HOOKUP_OBJECT (mod_hebergement, button_mod, "button_mod");
  GLADE_HOOKUP_OBJECT (mod_hebergement, alignment80, "alignment80");
  GLADE_HOOKUP_OBJECT (mod_hebergement, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (mod_hebergement, image40, "image40");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label12000, "label12000");
  GLADE_HOOKUP_OBJECT (mod_hebergement, check_id, "check_id");
  GLADE_HOOKUP_OBJECT (mod_hebergement, alignment700, "alignment700");
  GLADE_HOOKUP_OBJECT (mod_hebergement, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (mod_hebergement, image30, "image30");
  GLADE_HOOKUP_OBJECT (mod_hebergement, label1100, "label1100");

  return mod_hebergement;
}

GtkWidget*
create_aj_hebergement (void)
{
  GtkWidget *aj_hebergement;
  GtkWidget *fixed5d;
  GtkWidget *aj5;
  GtkWidget *ajc;
  GtkWidget *aj2;
  GtkWidget *aj3;
  GtkWidget *aj6;
  GtkWidget *aj1;
  GtkObject *aj7_adj;
  GtkWidget *aj7;
  GtkWidget *label1600;
  GtkWidget *label1700;
  GtkWidget *label1800;
  GtkWidget *label3500;
  GtkWidget *label2300;
  GtkWidget *label2000;
  GtkWidget *label1300;
  GtkWidget *label1900;
  GtkWidget *label1400;
  GtkWidget *image108;
  GtkWidget *ajA;
  GSList *ajA_group = NULL;
  GtkWidget *ajB;
  GtkWidget *ajC;
  GtkWidget *aj4;
  GtkWidget *button_aj;
  GtkWidget *alignment10;
  GtkWidget *hbox6;
  GtkWidget *image60;
  GtkWidget *label21000;

  aj_hebergement = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (aj_hebergement, 784, 720);
  gtk_window_set_title (GTK_WINDOW (aj_hebergement), _("Ajouter un \303\251tudiant h\303\251berg\303\251"));
  gtk_window_set_position (GTK_WINDOW (aj_hebergement), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (aj_hebergement), FALSE);

  fixed5d = gtk_fixed_new ();
  gtk_widget_show (fixed5d);
  gtk_container_add (GTK_CONTAINER (aj_hebergement), fixed5d);

  aj5 = gtk_entry_new ();
  gtk_widget_show (aj5);
  gtk_fixed_put (GTK_FIXED (fixed5d), aj5, 152, 608);
  gtk_widget_set_size_request (aj5, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj5), 8226);

  ajc = gtk_calendar_new ();
  gtk_widget_show (ajc);
  gtk_fixed_put (GTK_FIXED (fixed5d), ajc, 248, 312);
  gtk_widget_set_size_request (ajc, 216, 184);
  gtk_calendar_display_options (GTK_CALENDAR (ajc),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  aj2 = gtk_entry_new ();
  gtk_widget_show (aj2);
  gtk_fixed_put (GTK_FIXED (fixed5d), aj2, 168, 200);
  gtk_widget_set_size_request (aj2, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj2), 8226);

  aj3 = gtk_entry_new ();
  gtk_widget_show (aj3);
  gtk_fixed_put (GTK_FIXED (fixed5d), aj3, 168, 248);
  gtk_widget_set_size_request (aj3, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj3), 8226);

  aj6 = gtk_entry_new ();
  gtk_widget_show (aj6);
  gtk_fixed_put (GTK_FIXED (fixed5d), aj6, 152, 656);
  gtk_widget_set_size_request (aj6, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj6), 8226);

  aj1 = gtk_entry_new ();
  gtk_widget_show (aj1);
  gtk_fixed_put (GTK_FIXED (fixed5d), aj1, 168, 152);
  gtk_widget_set_size_request (aj1, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (aj1), 8226);

  aj7_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  aj7 = gtk_spin_button_new (GTK_ADJUSTMENT (aj7_adj), 1, 0);
  gtk_widget_show (aj7);
  gtk_fixed_put (GTK_FIXED (fixed5d), aj7, 512, 560);
  gtk_widget_set_size_request (aj7, 60, 27);

  label1600 = gtk_label_new (_("Email :"));
  gtk_widget_show (label1600);
  gtk_fixed_put (GTK_FIXED (fixed5d), label1600, 64, 672);
  gtk_widget_set_size_request (label1600, 57, 17);

  label1700 = gtk_label_new (_("Tel :"));
  gtk_widget_show (label1700);
  gtk_fixed_put (GTK_FIXED (fixed5d), label1700, 64, 616);
  gtk_widget_set_size_request (label1700, 56, 16);

  label1800 = gtk_label_new (_("Type chambre :"));
  gtk_widget_show (label1800);
  gtk_fixed_put (GTK_FIXED (fixed5d), label1800, 40, 560);
  gtk_widget_set_size_request (label1800, 112, 24);

  label3500 = gtk_label_new (_("Num chambre :"));
  gtk_widget_show (label3500);
  gtk_fixed_put (GTK_FIXED (fixed5d), label3500, 368, 560);
  gtk_widget_set_size_request (label3500, 112, 24);

  label2300 = gtk_label_new (_("Bloc :"));
  gtk_widget_show (label2300);
  gtk_fixed_put (GTK_FIXED (fixed5d), label2300, 32, 512);
  gtk_widget_set_size_request (label2300, 112, 24);

  label2000 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label2000);
  gtk_fixed_put (GTK_FIXED (fixed5d), label2000, 8, 304);
  gtk_widget_set_size_request (label2000, 152, 32);

  label1300 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label1300);
  gtk_fixed_put (GTK_FIXED (fixed5d), label1300, 48, 256);
  gtk_widget_set_size_request (label1300, 64, 16);

  label1900 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label1900);
  gtk_fixed_put (GTK_FIXED (fixed5d), label1900, 40, 208);
  gtk_widget_set_size_request (label1900, 80, 24);

  label1400 = gtk_label_new (_("ID :"));
  gtk_widget_show (label1400);
  gtk_fixed_put (GTK_FIXED (fixed5d), label1400, 64, 168);
  gtk_widget_set_size_request (label1400, 40, 16);

  image108 = create_pixmap (aj_hebergement, "logos.png");
  gtk_widget_show (image108);
  gtk_fixed_put (GTK_FIXED (fixed5d), image108, 0, 16);
  gtk_widget_set_size_request (image108, 218, 116);

  ajA = gtk_radio_button_new_with_mnemonic (NULL, _("A"));
  gtk_widget_show (ajA);
  gtk_fixed_put (GTK_FIXED (fixed5d), ajA, 184, 512);
  gtk_widget_set_size_request (ajA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajA), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajA));

  ajB = gtk_radio_button_new_with_mnemonic (NULL, _("B"));
  gtk_widget_show (ajB);
  gtk_fixed_put (GTK_FIXED (fixed5d), ajB, 360, 512);
  gtk_widget_set_size_request (ajB, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajB), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajB));

  ajC = gtk_radio_button_new_with_mnemonic (NULL, _("C"));
  gtk_widget_show (ajC);
  gtk_fixed_put (GTK_FIXED (fixed5d), ajC, 504, 512);
  gtk_widget_set_size_request (ajC, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ajC), ajA_group);
  ajA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ajC));

  aj4 = gtk_combo_box_new_text ();
  gtk_widget_show (aj4);
  gtk_fixed_put (GTK_FIXED (fixed5d), aj4, 160, 552);
  gtk_widget_set_size_request (aj4, 176, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("Individuelle"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("Double"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (aj4), _("Triple"));

  button_aj = gtk_button_new ();
  gtk_widget_show (button_aj);
  gtk_fixed_put (GTK_FIXED (fixed5d), button_aj, 600, 632);
  gtk_widget_set_size_request (button_aj, 120, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_aj), alignment10);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox6);

  image60 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox6), image60, FALSE, FALSE, 0);

  label21000 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label21000);
  gtk_box_pack_start (GTK_BOX (hbox6), label21000, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_aj, "clicked",
                    G_CALLBACK (on_button_aj_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aj_hebergement, aj_hebergement, "aj_hebergement");
  GLADE_HOOKUP_OBJECT (aj_hebergement, fixed5d, "fixed5d");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj5, "aj5");
  GLADE_HOOKUP_OBJECT (aj_hebergement, ajc, "ajc");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj2, "aj2");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj3, "aj3");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj6, "aj6");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj1, "aj1");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj7, "aj7");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label1600, "label1600");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label1700, "label1700");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label1800, "label1800");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label3500, "label3500");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label2300, "label2300");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label2000, "label2000");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label1300, "label1300");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label1900, "label1900");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label1400, "label1400");
  GLADE_HOOKUP_OBJECT (aj_hebergement, image108, "image108");
  GLADE_HOOKUP_OBJECT (aj_hebergement, ajA, "ajA");
  GLADE_HOOKUP_OBJECT (aj_hebergement, ajB, "ajB");
  GLADE_HOOKUP_OBJECT (aj_hebergement, ajC, "ajC");
  GLADE_HOOKUP_OBJECT (aj_hebergement, aj4, "aj4");
  GLADE_HOOKUP_OBJECT (aj_hebergement, button_aj, "button_aj");
  GLADE_HOOKUP_OBJECT (aj_hebergement, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (aj_hebergement, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (aj_hebergement, image60, "image60");
  GLADE_HOOKUP_OBJECT (aj_hebergement, label21000, "label21000");

  return aj_hebergement;
}

GtkWidget*
create_recherche (void)
{
  GtkWidget *recherche;
  GtkWidget *fixed6d;
  GtkWidget *r1;
  GtkWidget *label3100;
  GtkWidget *label3400;
  GtkWidget *label3200;
  GtkWidget *label3800;
  GtkWidget *label2500;
  GtkWidget *label2400;
  GtkWidget *label3000;
  GtkWidget *label2700;
  GtkWidget *image109;
  GtkWidget *label3900;
  GtkWidget *chercher;
  GtkWidget *alignment120;
  GtkWidget *hbox8;
  GtkWidget *image80;
  GtkWidget *label3300;
  GtkWidget *r2;
  GtkWidget *r3;
  GtkWidget *r4;
  GtkWidget *r5;
  GtkWidget *r6;
  GtkWidget *r9;
  GtkWidget *r7;
  GtkWidget *r8;

  recherche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (recherche, 784, 720);
  gtk_window_set_title (GTK_WINDOW (recherche), _("Chercher un \303\251tudiant h\303\251berg\303\251"));
  gtk_window_set_position (GTK_WINDOW (recherche), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (recherche), FALSE);

  fixed6d = gtk_fixed_new ();
  gtk_widget_show (fixed6d);
  gtk_container_add (GTK_CONTAINER (recherche), fixed6d);

  r1 = gtk_entry_new ();
  gtk_widget_show (r1);
  gtk_fixed_put (GTK_FIXED (fixed6d), r1, 336, 64);
  gtk_widget_set_size_request (r1, 144, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (r1), 8226);

  label3100 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label3100);
  gtk_fixed_put (GTK_FIXED (fixed6d), label3100, 72, 256);
  gtk_widget_set_size_request (label3100, 64, 16);

  label3400 = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label3400);
  gtk_fixed_put (GTK_FIXED (fixed6d), label3400, 24, 320);
  gtk_widget_set_size_request (label3400, 144, 16);

  label3200 = gtk_label_new (_("Bloc :"));
  gtk_widget_show (label3200);
  gtk_fixed_put (GTK_FIXED (fixed6d), label3200, 72, 392);
  gtk_widget_set_size_request (label3200, 64, 16);

  label3800 = gtk_label_new (_("Type chambre :"));
  gtk_widget_show (label3800);
  gtk_fixed_put (GTK_FIXED (fixed6d), label3800, 16, 464);
  gtk_widget_set_size_request (label3800, 112, 24);

  label2500 = gtk_label_new (_("Tel :"));
  gtk_widget_show (label2500);
  gtk_fixed_put (GTK_FIXED (fixed6d), label2500, 72, 528);
  gtk_widget_set_size_request (label2500, 56, 16);

  label2400 = gtk_label_new (_("Email :"));
  gtk_widget_show (label2400);
  gtk_fixed_put (GTK_FIXED (fixed6d), label2400, 64, 584);
  gtk_widget_set_size_request (label2400, 57, 17);

  label3000 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label3000);
  gtk_fixed_put (GTK_FIXED (fixed6d), label3000, 64, 184);
  gtk_widget_set_size_request (label3000, 80, 24);

  label2700 = gtk_label_new (_("ID :"));
  gtk_widget_show (label2700);
  gtk_fixed_put (GTK_FIXED (fixed6d), label2700, 256, 72);
  gtk_widget_set_size_request (label2700, 40, 16);

  image109 = create_pixmap (recherche, "logos.png");
  gtk_widget_show (image109);
  gtk_fixed_put (GTK_FIXED (fixed6d), image109, 8, 8);
  gtk_widget_set_size_request (image109, 218, 116);

  label3900 = gtk_label_new (_("Num chambre :"));
  gtk_widget_show (label3900);
  gtk_fixed_put (GTK_FIXED (fixed6d), label3900, 456, 464);
  gtk_widget_set_size_request (label3900, 112, 24);

  chercher = gtk_button_new ();
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed6d), chercher, 608, 56);
  gtk_widget_set_size_request (chercher, 104, 48);

  alignment120 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment120);
  gtk_container_add (GTK_CONTAINER (chercher), alignment120);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment120), hbox8);

  image80 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image80);
  gtk_box_pack_start (GTK_BOX (hbox8), image80, FALSE, FALSE, 0);

  label3300 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label3300);
  gtk_box_pack_start (GTK_BOX (hbox8), label3300, FALSE, FALSE, 0);

  r2 = gtk_label_new ("");
  gtk_widget_show (r2);
  gtk_fixed_put (GTK_FIXED (fixed6d), r2, 224, 184);
  gtk_widget_set_size_request (r2, 232, 32);

  r3 = gtk_label_new ("");
  gtk_widget_show (r3);
  gtk_fixed_put (GTK_FIXED (fixed6d), r3, 224, 248);
  gtk_widget_set_size_request (r3, 232, 32);

  r4 = gtk_label_new ("");
  gtk_widget_show (r4);
  gtk_fixed_put (GTK_FIXED (fixed6d), r4, 224, 312);
  gtk_widget_set_size_request (r4, 232, 32);

  r5 = gtk_label_new ("");
  gtk_widget_show (r5);
  gtk_fixed_put (GTK_FIXED (fixed6d), r5, 224, 384);
  gtk_widget_set_size_request (r5, 232, 32);

  r6 = gtk_label_new ("");
  gtk_widget_show (r6);
  gtk_fixed_put (GTK_FIXED (fixed6d), r6, 224, 456);
  gtk_widget_set_size_request (r6, 232, 32);

  r9 = gtk_label_new ("");
  gtk_widget_show (r9);
  gtk_fixed_put (GTK_FIXED (fixed6d), r9, 624, 464);
  gtk_widget_set_size_request (r9, 49, 17);

  r7 = gtk_label_new ("");
  gtk_widget_show (r7);
  gtk_fixed_put (GTK_FIXED (fixed6d), r7, 224, 520);
  gtk_widget_set_size_request (r7, 232, 32);

  r8 = gtk_label_new ("");
  gtk_widget_show (r8);
  gtk_fixed_put (GTK_FIXED (fixed6d), r8, 224, 576);
  gtk_widget_set_size_request (r8, 232, 32);

  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (recherche, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (recherche, fixed6d, "fixed6d");
  GLADE_HOOKUP_OBJECT (recherche, r1, "r1");
  GLADE_HOOKUP_OBJECT (recherche, label3100, "label3100");
  GLADE_HOOKUP_OBJECT (recherche, label3400, "label3400");
  GLADE_HOOKUP_OBJECT (recherche, label3200, "label3200");
  GLADE_HOOKUP_OBJECT (recherche, label3800, "label3800");
  GLADE_HOOKUP_OBJECT (recherche, label2500, "label2500");
  GLADE_HOOKUP_OBJECT (recherche, label2400, "label2400");
  GLADE_HOOKUP_OBJECT (recherche, label3000, "label3000");
  GLADE_HOOKUP_OBJECT (recherche, label2700, "label2700");
  GLADE_HOOKUP_OBJECT (recherche, image109, "image109");
  GLADE_HOOKUP_OBJECT (recherche, label3900, "label3900");
  GLADE_HOOKUP_OBJECT (recherche, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (recherche, alignment120, "alignment120");
  GLADE_HOOKUP_OBJECT (recherche, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (recherche, image80, "image80");
  GLADE_HOOKUP_OBJECT (recherche, label3300, "label3300");
  GLADE_HOOKUP_OBJECT (recherche, r2, "r2");
  GLADE_HOOKUP_OBJECT (recherche, r3, "r3");
  GLADE_HOOKUP_OBJECT (recherche, r4, "r4");
  GLADE_HOOKUP_OBJECT (recherche, r5, "r5");
  GLADE_HOOKUP_OBJECT (recherche, r6, "r6");
  GLADE_HOOKUP_OBJECT (recherche, r9, "r9");
  GLADE_HOOKUP_OBJECT (recherche, r7, "r7");
  GLADE_HOOKUP_OBJECT (recherche, r8, "r8");

  return recherche;
}

